### ISSUE TITLE
Get predictor matrix for pseudotime using a gamList with one lineage 

### ISSUE THREAD

**Issue by yu-tong-wang** [statOmics/tradeSeqPaper#3]
Hi all,

I am trying to create a predictor matrix for a range of pseudotime to plot a heatmap like your fig 6c using my dataset. After following ./fletcher/20180830_caseStudyFletcher_v5_tradeR.Rmd, I could run fitGAM on my dataset (~ 14k genes and 1k cells) with only one lineage specified, as well as run the associationTest. However, I got error for line 365 in 20180830_caseStudyFletcher_v5_tradeR.Rmd, i.e.,` df <- .getPredictRangeDf(gamList[[1]], lineageId = 1, nPoints = 100)`.

The error message I got is that `Error in vars[, grep(colnames(vars), pattern = "t[1-9]")] <- 0 : 
  incorrect number of subscripts on matrix`. I think it is because the structure & data type of my `dm = gamList[[1]]` is different from the data frame that you had in your original analysis. 

Could you specify the list structure of `gamList` in your analysis? How would you recommend to extract the data frame (which is `dm = gamList[[1]]` in your analysis) from a `gamList` when there is only one lineage in my analysis? Or could you suggest how to modify the utility function `.getPredictRangeDf`? I had a long and hard time trying to interpret what each line in `.getPredictRangeDf` is trying to do, without knowing your data structure from the very beginning. I could not reproduce your analysis and see what your data structure was like because of the concern of time, for instance, `zinbFit` and `fitGAM` would take a very long time to run.

My `gamList` is a large list of length 14k, equal to the number of genes. Thus, `gamList[[1]]` is a `gam glm lm` object for one gene in my output, rather than a data frame. I suspect that it is because I only specified one lineage for my dataset, for the sake of biological interpretation. 

Thank you! 

---------------------
Update: After setting `sce = T`, my `gamList` object is a SingleCellExperiment object now. Then I have two questions in order to create the predictor matrix:

(1) Does `df <- .getPredictRangeDf(gam_list[[1]], lineageId = 1, nPoints = 100)` intend to create evenly-distributed grids across the pseudotime, and also set the starting point to be zero? If this is what `.getPredictRangeDf` intended to do, I have done this step correctly. 
(2) When I tried to use `predict` function to create the predictor matrix following line 366 in 20180830_caseStudyFletcher_v5_tradeR.Rmd, i.e., `y <- do.call(rbind, lapply(gam_list[top200Assoc], predict, newdata = df, type = "link"))`, I got an error because `predict` cannot be applied to SingleCellExperiment object, which is `gam_list[top200Assoc]` in the original code. I assume that `predict` is `stats::predict` and there is some way to extract the regression model from gam_list and feed the model to `predict`, is this correct? If so, any suggestion how I could find such model in the gam_list object? Or should I actually use `tradeSeq::predictSmooth` instead?

```
> y <- do.call(rbind, lapply(gam_list[top200Assoc], stats::predict, newdata = df, type = "link"))
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'args' in selecting a method for function 'do.call': no applicable method for 'predict' applied to an object of class "c('SingleCellExperiment', 'RangedSummarizedExperiment', 'SummarizedExperiment', 'Vector', 'Annotated', 'vector_OR_Vector')"
```

**Comment by koenvandenberge** [comment]
Hi @yu-tong-wang 

My apologies for taking so long getting back to you.

If you're trying to get to the fitted values for each cell, or the estimated smoother, I recommend you use the `predictCells` or `predictSmooth` functions in `tradeSeq`. I do not recommend following the code on the case study in this repo, since that is based on an older version of `tradeSeq`.

I would recommend to refit your models using an updated version of `tradeSeq` such that you have a `SingleCellExperiment` output and not a list output. Then you can follow along with the vignette, in particular the [section on Clustering genes according to their expression pattern](https://bioconductor.org/packages/release/bioc/vignettes/tradeSeq/inst/doc/tradeSeq.html#clustering-of-genes-according-to-their-expression-pattern) would be relevant for you. You can just set `gene = rownames(sce)` as argument there to get the output for all genes.

Let me know if there'd be any additional questions.

**Comment by yu-tong-wang** [comment]
Thank you for the clear clarification and the reference, @koenvandenberge. This answered a lot of my previous questions, and `predictCells` is super helpful.
